document.write("<div class=\"w_cont_box\">");
document.writeln('');document.write("<style type=\"text/css\">");
document.writeln('');document.write("<!--");
document.writeln('');document.write("");
document.writeln('');document.write(".sv_cont_c12{text-align:left;color:#000;font-size:12px;margin:0 5px 0;font-family: \"Microsoft Yahei\",\"SimSun\";}");
document.writeln('');document.write(".sv_cont_c12 form{padding:0 0 10px;background-image:none;}");
document.writeln('');document.write(".sv_cont_c12 .sv_title{padding:14px 0 4px 23px;background:url(http://survey.news.sina.com.cn/images/specialImplant/item_caps.png) no-repeat 0 16.5px;font-size: 14px;line-height: 18px;color: #000;}");
document.writeln('');document.write(".sv_cont_c12 .sv_list{padding-left:18px; color: #6c6c6c;}");
document.writeln('');document.write(".sv_cont_c12 .sv_option{zoom:1;overflow:hidden;}");
document.writeln('');document.write(".sv_cont_c12 .sv_option_1{padding-left:5px;}");
document.writeln('');document.write(".sv_cont_c12 .sv_element{width:22px;float:left;*margin-right:-3px;padding-top: 4px;padding-top: 0px\\9;padding-left: 1px;}");
document.writeln('');document.write(".sv_cont_c12 .sv_txt{margin-left:22px;zoom:1;line-height: 16px;padding: 3px 0;}");
document.writeln('');document.write(".sv_cont_c12 .sv_txt2{margin-left:22px;line-height: 16px;text-align:center;zoom:1;padding:5px 0 0;}");
document.writeln('');document.write(".sv_cont_c12 .sv_buttons{text-align:left;padding:5px 0 0 22px;}");
document.writeln('');document.write("/* modified 0905 */");
document.writeln('');document.write(".sv_cont_c12 .sv_buttons * {vertical-align: middle;}");
document.writeln('');document.write(".sv_cont_c12 .sv_buttons input {width: 58px;height: 21px;border: 1px solid #f29149;border-radius: 3px;background-color:#f29149;color:#fff;text-align: center;cursor: pointer;font-family: \"Microsoft Yahei\",\"SimSun\";line-height: 17px;margin-right: 8px;}");
document.writeln('');document.write("/* ./modified 0905 */");
document.writeln('');document.write(".sv_cont_c12 .sv_buttons .submit-mover {background-color: #fff;border-color: #e3e3e3;color: #f29149;}");
document.writeln('');document.write(".sv_cont_c12 .sv_buttons a {display: inline-block;height: 19px;line-height: 19px;text-align: center;width: 58px;border-radius: 3px;}");
document.writeln('');document.write(".sv_cont_c12 .sv_buttons a:link, .sv_cont_c12 .sv_buttons a:visited {background-color:#f29149;color:#fff;text-decoration: none;border: 1px solid #f29149;}");
document.writeln('');document.write(".sv_cont_c12 .sv_buttons a:hover, .sv_cont_c12 .sv_buttons a:focus, .sv_cont_c12 .sv_buttons a:active {background-color: #fff;border-color: #e3e3e3;color: #f29149;text-decoration: none;}");
document.writeln('');document.write("/* added 0830 */");
document.writeln('');document.write(".sv_cont_c12 .sv_buttons .sv_submit:link, .sv_cont_c12 .sv_buttons .sv_submit:visited {border: 1px solid #f29149;border-radius: 3px;background-color:#f29149;color:#fff;}");
document.writeln('');document.write(".sv_cont_c12 .sv_buttons .sv_submit:hover, .sv_cont_c12 .sv_buttons .sv_submit:focus, .sv_cont_c12 .sv_buttons .sv_submit:active {background-color: #fff;border-color: #e3e3e3;color: #f29149;}");
document.writeln('');document.write("/* ./added 0830 */");
document.writeln('');document.write(".sv_cont_c12 .sv_line{background:url(http://www.sinaimg.cn/dy/2009/0112/sv/sv_mj_002.gif)");
document.writeln('');document.write("repeat-x 0 50%;height:25px;overflow:hidden;}");
document.writeln('');document.write(".sv_cont_c12 .c_grey{color:#999;}");
document.writeln('');document.write(".sv_cont_c12 .sv_login{text-align:center;}");
document.writeln('');document.write("");
document.writeln('');document.write("");
document.writeln('');document.write("");
document.writeln('');document.write("");
document.writeln('');document.write("/* added 0905 */");
document.writeln('');document.write(".sv_cont_c12 .sv_buttons .sv_unablesubmit, .sv_cont_c12 .sv_buttons .sv_joined,.sv_cont_c12 .sv_buttons .sv_stoped ,.sv_cont_c12 .sv_buttons  .sv_ended{background-color: #cfcfcf;color: #8e8e8e;border: 1px solid #cfcfcf;border-radius: 3px;display: inline-block;text-align: center;width: 58px;height: 19px;line-height: 19px;margin-right: 8px;cursor: default;}");
document.writeln('');document.write(".sv_cont_c12 .sv_login_wrap {position: relative;padding-left: 22px;}");
document.writeln('');document.write(".sv_cont_c12 .sv_login_wrap .sv_login_title {color: #e60012;background: url(http://survey.news.sina.com.cn/images/histogram.png) -145px -80px no-repeat;padding-left: 20px;line-height: 26px;color: #000;}");
document.writeln('');document.write(".sv_cont_c12 .sv_login_title a:link, .sv_cont_c12 .sv_login_title a:visited, .sv_cont_c12 .sv_login_title a:hover, .sv_cont_c12 .sv_login_title a:focus, .sv_cont_c12 .sv_login_title a:active {color: #ff8500;text-decoration: none;}");
document.writeln('');document.write(".sv_cont_c12 .sv_login_box {position: absolute;z-index: 9999;left: 0px;top:-140px;_left:-42px;background-color: #fff;border: 2px solid #e5e5e5;border-radius: 3px;padding: 5px 20px 5px 22px;width: 205px;}");
document.writeln('');document.write(".sv_cont_c12 .sv_box_closer {position: absolute;z-index: 99999;right: 5px;top: 2px;color: #999;font-size: 16px;text-decoration: none;}");
document.writeln('');document.write(".sv_cont_c12 .sv_box_closer:visited {color: #999;}");
document.writeln('');document.write(".sv_cont_c12 .sv_box_closer:hover, .sv_cont_c12 .sv_box_closer:active, .sv_cont_c12 .sv_box_closer:focus {color: #f00;}");
document.writeln('');document.write(".sv_cont_c12 .sv_login_box .sv_login_error {color: #e60012;background: url(http://survey.news.sina.com.cn/images/histogram.png) -145px -84px no-repeat;padding-left: 20px;line-height: 20px;height:20px;overflow: hidden;}");
document.writeln('');document.write(".sv_cont_c12 .sv_login_box .sv_need_login {color: #000;}");
document.writeln('');document.write(".sv_cont_c12 .sv_login_box .sv_login_tips {line-height: 26px;color: #f29149;font-size: 16px;vertical-align: middle;padding-left: 5px;*vertical-align: 2px;}");
document.writeln('');document.write(".sv_cont_c12 .sv_login_input {width: 180px;height: 22px;line-height:22px;border: 1px solid #d0d0d0;padding-left: 5px;color: #000;font-family: \"Microsoft Yahei\",\"SimSun\";}");
document.writeln('');document.write(".sv_cont_c12 .sv_username, .sv_cont_c12 .sv_password {margin-top: 5px;}");
document.writeln('');document.write(".sv_cont_c12 .sv_password {position: relative;}");
document.writeln('');document.write(".sv_cont_c12 .sv_password .sv_login_psw {}");
document.writeln('');document.write(".sv_cont_c12 .sv_password .sv_login_psw_holder {position: absolute;z-index: 200;left: 0px;top: 0px;*top: 3px;}");
document.writeln('');document.write(".sv_cont_c12 .sv_handler {margin: 5px 0;}");
document.writeln('');document.write(".sv_cont_c12 .sv_handler .sv_handler_links {float: left;display: inline;height: 29px;line-height: 29px;}");
document.writeln('');document.write(".sv_cont_c12 .sv_handler_links a:link, .sv_cont_c12 .sv_handler_links a:visited {color: #f29149;text-decoration: none;}");
document.writeln('');document.write(".sv_cont_c12 .sv_handler_links a:hover, .sv_cont_c12 .sv_handler_links a:active, .sv_cont_c12 .sv_handler_links a:focus {color: #f29149;text-decoration: underline;}");
document.writeln('');document.write(".sv_cont_c12 .sv_handler_login, .sv_cont_c12 .sv_handler_login:visited {color: #fff;width: 64px;height: 29px;line-height: 29px;background-color: #ff8500;text-align: center;float: right;display: inline;text-decoration: none;margin-right: 12px;}");
document.writeln('');document.write(".sv_cont_c12 .sv_handler_login:hover, .sv_cont_c12 .sv_handler_login:active, .sv_cont_c12 .sv_handler_login:focus {opacity: 0.8;filter:alpha(opacity=80);}");
document.writeln('');document.write(".sv_cont_c12 .sv_blank {clear: both;height: 0px;overflow: hidden;}");
document.writeln('');document.write(".sv_cont_c12 input[type=\"submit\"]{-webkit-appearance:none;}");
document.writeln('');document.write("/* ./added 0905 */");
document.writeln('');document.write("");
document.writeln('');document.write("-->");
document.writeln('');document.write("</style>");
document.writeln('');document.write("<div class=\"sv_cont_c12\" id=\"SINA_SURVERY_TOPIC_EMBED_FRAME110299\" needlogin=\"1\">");
document.writeln('');document.write("<form name=\"survey_110299\" action=\"http://survey.sports.sina.com.cn/polling.php\" method=\"post\" target=\"_blank\">");
document.writeln('');document.write("<div class=\"sv_title\">您认为本赛季英超谁将问鼎冠军？</div>");
document.writeln('');document.write("<div class=\"sv_list\">");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23324\" value=\"147358\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">切尔西</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23324\" value=\"147359\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">曼城</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23324\" value=\"147360\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">曼联</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23324\" value=\"147361\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">阿森纳</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23324\" value=\"147362\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">利物浦</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23324\" value=\"147363\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">其他球队</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_title\">您认为本赛季谁将摘得英超金靴？</div>");
document.writeln('');document.write("<div class=\"sv_list\">");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23325\" value=\"147364\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">阿圭罗</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23325\" value=\"147365\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">迭戈-科斯塔</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23325\" value=\"147366\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">哈里-凯恩</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23325\" value=\"147367\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">本特克</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23325\" value=\"147368\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">鲁尼</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23325\" value=\"147369\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">桑切斯</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23325\" value=\"147370\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">阿扎尔</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23325\" value=\"147371\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">斯特林</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23325\" value=\"147372\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">吉鲁</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_option\">");
document.writeln('');document.write("<div class=\"sv_element\"><input  type=\"radio\" name=\"q_23325\" value=\"147373\"></div>");
document.writeln('');document.write("<div class=\"sv_txt\">其他人选</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("");
document.writeln('');document.write("");
document.writeln('');document.write("<div class=\"sv_login_wrap\">");
document.writeln('');document.write("<div class=\"sv_login_title\" style=\"display:none\" >您还未登录，该调查需要<a href=\"javascript:;\" style=\"color:#f29149;\" class=\"sv_login_btn\">登录</a>参与</div>");
document.writeln('');document.write("<div class=\"sv_login_box\" style=\"display:none\">");
document.writeln('');document.write("<div class=\"sv_login_error\" style=\"visibility:hidden\"></div>");
document.writeln('');document.write("<a href=\"javascript:;\" class=\"sv_box_closer\">×</a>");
document.writeln('');document.write("<div class=\"sv_username\">");
document.writeln('');document.write("<input  type=\"text\" class=\"sv_login_input\" placeholder=\"微博账号\" supportplaceholder=\"微博账号\" name=\"name\" /><span class=\"sv_login_tips\">*</span>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_password\">");
document.writeln('');document.write("<input  type=\"text\" class=\"sv_login_input sv_login_psw_holder\" value=\"请输入密码\" style=\"display:none\" />");
document.writeln('');document.write("<input  type=\"password\" class=\"sv_login_input sv_login_psw\" placeholder=\"请输入密码\" supportplaceholder=\"请输入密码\" name=\"password\" /><span class=\"sv_login_tips\">*</span>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_handler\">");
document.writeln('');document.write("<div class=\"sv_handler_links\">");
document.writeln('');document.write("<a href=\"http://login.sina.com.cn/forgot/index?entry=sso\" target=\"_blank\">忘记密码</a>&nbsp;&nbsp;<a href=\"http://weibo.com/signup/signup.php\" target=\"_blank\">立即注册</a>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<a href=\"javascript:;\" class=\"sv_handler_login\">登录</a>");
document.writeln('');document.write("<div class=\"sv_blank\"></div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("<div class=\"sv_buttons\">");
document.writeln('');document.write("<input   type=\"submit\" title=\"提交\" value=\"提交\" id=\"sv_submit\" onmouseover=\"this.className=\'submit-mover\'\" onmouseout=\"this.className=\'\'\" />");
document.writeln('');document.write("<span class=\"sv_unablesubmit\" style=\"display:none\">提交</span>");
document.writeln('');document.write("<span class=\"sv_joined\" style=\"display:none\">已参与</span>");
document.writeln('');document.write("<a title=\"查看\" target=\"_blank\" href=\"http://survey.sports.sina.com.cn/result/110299.html\">查看结果</a>");
document.writeln('');document.write("<input  type=\"hidden\" name=\"poll_id\" value=\"110299\">");
document.writeln('');document.write("<input  type=\"hidden\" name=\"ad_url\" value=\"\">");
document.writeln('');document.write("</div>");
document.writeln('');document.write("</form>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("</div>");
document.writeln('');document.write("");
document.writeln('');document.write("<script type=\"text/javascript\">");
document.writeln('');document.write(";(function(window, undefined) {");
document.writeln('');document.write("var window 				= window");
document.writeln('');document.write(", document 				= window.document");
document.writeln('');document.write(", _trim 				= String.prototype.trim");
document.writeln('');document.write("");
document.writeln('');document.write(", WRAP_ID 			= \'SINA_SURVERY_TOPIC_EMBED_FRAME110299\'");
document.writeln('');document.write("");
document.writeln('');document.write("");
document.writeln('');document.write(", supportPlaceHolder 	= \'placeholder\' in document.createElement(\'input\')");
document.writeln('');document.write("");
document.writeln('');document.write("");
document.writeln('');document.write("");
document.writeln('');document.write("//  Utils");
document.writeln('');document.write(", utils = {");
document.writeln('');document.write("trim : _trim && !_trim.call(\"\\uFEFF\\xA0\") ?");
document.writeln('');document.write("function( text ) {");
document.writeln('');document.write("return text == null ?");
document.writeln('');document.write("\"\" :");
document.writeln('');document.write("_trim.call( text );");
document.writeln('');document.write("} :");
document.writeln('');document.write("// Otherwise use our own trimming functionality");
document.writeln('');document.write("function( text ) {");
document.writeln('');document.write("return text == null ?");
document.writeln('');document.write("\"\" :");
document.writeln('');document.write("( text + \"\" ).replace( /^[\\s\\uFEFF\\xA0]+|[\\s\\uFEFF\\xA0]+$/g, \"\" );");
document.writeln('');document.write("}");
document.writeln('');document.write(",GD : function(id) {");
document.writeln('');document.write("if( !id ) {");
document.writeln('');document.write("return undefined;");
document.writeln('');document.write("} else if( typeof id === \"object\" && !!id.nodeType) {");
document.writeln('');document.write("return id;");
document.writeln('');document.write("} else {");
document.writeln('');document.write("return document.getElementById(id);");
document.writeln('');document.write("}");
document.writeln('');document.write("},");
document.writeln('');document.write("GN : function(tag,elem) {");
document.writeln('');document.write("elem = elem || document;");
document.writeln('');document.write("return elem.getElementsByTagName(tag);");
document.writeln('');document.write("},");
document.writeln('');document.write("GC : function(clz,el,tg){");
document.writeln('');document.write("el = el || document;");
document.writeln('');document.write("el = typeof(el) === \'string\' ? this.GD(el) : el;");
document.writeln('');document.write("tg = tg || \'*\';");
document.writeln('');document.write("var rs = [];");
document.writeln('');document.write("clz = \" \" + clz +\" \";");
document.writeln('');document.write("var cldr = this.GN(tg,el), len = cldr.length;");
document.writeln('');document.write("for (var i = 0; i < len; ++ i){");
document.writeln('');document.write("var o = cldr[i];");
document.writeln('');document.write("if (o.nodeType == 1){");
document.writeln('');document.write("var ecl = \" \" + o.className + \" \";");
document.writeln('');document.write("if (ecl.indexOf(clz) != -1){");
document.writeln('');document.write("rs[rs.length] = o;");
document.writeln('');document.write("}");
document.writeln('');document.write("}");
document.writeln('');document.write("}");
document.writeln('');document.write("return rs;");
document.writeln('');document.write("},");
document.writeln('');document.write("GA : function(attname, parentId, tagname) {");
document.writeln('');document.write("if (typeof(parentId) === \'string\' && parentId != \'\') {");
document.writeln('');document.write("parentId = this.GD(parentId);");
document.writeln('');document.write("}");
document.writeln('');document.write("var elms = this.GN((tagname || \'*\'),(parentId || document)),");
document.writeln('');document.write("ret = [];");
document.writeln('');document.write("for (var i = 0,");
document.writeln('');document.write("l = elms.length; i < l; i++) {");
document.writeln('');document.write("if (elms[i].getAttribute(attname)) {");
document.writeln('');document.write("ret.push(elms[i]);");
document.writeln('');document.write("}");
document.writeln('');document.write("}");
document.writeln('');document.write("return ret;");
document.writeln('');document.write("},");
document.writeln('');document.write("GAC : function(attvalue, attname, parentId, tagname) {");
document.writeln('');document.write("if (typeof parentId === \'string\' && parentId != \'\') {");
document.writeln('');document.write("parentId = this.GD(parentId);");
document.writeln('');document.write("}");
document.writeln('');document.write("var elms =this.GN((tagname || \'*\'),(parentId || document)),");
document.writeln('');document.write("ret = [],");
document.writeln('');document.write("re = new RegExp(\'\\\\b\' + attvalue + \'\\\\b\');");
document.writeln('');document.write("for (var i = 0,");
document.writeln('');document.write("l = elms.length; i < l; i++) {");
document.writeln('');document.write("if (elms[i].getAttribute(attname) && re.test(elms[i].getAttribute(attname))) {");
document.writeln('');document.write("ret.push(elms[i]);");
document.writeln('');document.write("}");
document.writeln('');document.write("}");
document.writeln('');document.write("return ret;");
document.writeln('');document.write("},");
document.writeln('');document.write("addEvent : function(obj, evt, func, eventobj) {");
document.writeln('');document.write("var eventobj = !eventobj ? obj : eventobj,");
document.writeln('');document.write("evt = evt || \'click\',");
document.writeln('');document.write("func = func || function(){};");
document.writeln('');document.write("");
document.writeln('');document.write("if( obj.addEventListener ) {");
document.writeln('');document.write("obj.addEventListener(evt, func, false);");
document.writeln('');document.write("} else if( eventobj.attachEvent ) {");
document.writeln('');document.write("obj.attachEvent(\'on\' + evt, func);");
document.writeln('');document.write("}");
document.writeln('');document.write("},");
document.writeln('');document.write("getcookie : function(name, nounescape) {");
document.writeln('');document.write("// name = cookiepre + name;");
document.writeln('');document.write("var cookie_start = document.cookie.indexOf(name);");
document.writeln('');document.write("var cookie_end = document.cookie.indexOf(\";\", cookie_start);");
document.writeln('');document.write("if(cookie_start == -1) {");
document.writeln('');document.write("return \'\';");
document.writeln('');document.write("} else {");
document.writeln('');document.write("var v = document.cookie.substring(cookie_start + name.length + 1, (cookie_end > cookie_start ? cookie_end : document.cookie.length));");
document.writeln('');document.write("return !nounescape ? unescape(v) : v;");
document.writeln('');document.write("}");
document.writeln('');document.write("},");
document.writeln('');document.write("jsonp : function(url, params, callback, callbackname, fix) {");
document.writeln('');document.write("var byId = this.GD;");
document.writeln('');document.write("var idStr = url+\'&\'+params;");
document.writeln('');document.write("var callbackname = callbackname || \'callback\';");
document.writeln('');document.write("var fun = \'\';");
document.writeln('');document.write("if (byId(url)) {");
document.writeln('');document.write("document.body.removeChild(byId(url));");
document.writeln('');document.write("}");
document.writeln('');document.write("fix = fix||false;");
document.writeln('');document.write("if(!fix){");
document.writeln('');document.write("url = url + ((url.indexOf(\'?\') == -1) ? \'?\' : \'&\') + \'_t=\' + Math.random();");
document.writeln('');document.write("if (typeof callback == \'function\') {");
document.writeln('');document.write("fun = \'fun_\' + new Date().getUTCMilliseconds() + (\'\' + Math.random()).substring(3);");
document.writeln('');document.write("eval(fun + \'=function(res){callback(res)}\');");
document.writeln('');document.write("}");
document.writeln('');document.write("}else{");
document.writeln('');document.write("url = url + ((url.indexOf(\'?\') == -1) ? \'?\' : \'&\') + \'_t=fixed\';");
document.writeln('');document.write("if(typeof callback == \'string\'){");
document.writeln('');document.write("fun = callback;");
document.writeln('');document.write("}");
document.writeln('');document.write("}");
document.writeln('');document.write("url = url + \'&\' + callbackname + \'=\' + fun;");
document.writeln('');document.write("url = url+\'&\'+params;");
document.writeln('');document.write("var head_dom = this.GN(\'head\')[0];");
document.writeln('');document.write("var old_script = byId(idStr);");
document.writeln('');document.write("if(old_script){");
document.writeln('');document.write("head_dom.removeChild(old_script);");
document.writeln('');document.write("}");
document.writeln('');document.write("var script_dom = document.createElement(\'script\');");
document.writeln('');document.write("script_dom.src  =   url;");
document.writeln('');document.write("script_dom.id   =   idStr;");
document.writeln('');document.write("script_dom.type =  \'text/javascript\';");
document.writeln('');document.write("script_dom.language = \'javascript\';");
document.writeln('');document.write("head_dom.appendChild(script_dom);");
document.writeln('');document.write("},");
document.writeln('');document.write("jsLoader : function(url,callback){");
document.writeln('');document.write("var s = document.createElement(\'script\');");
document.writeln('');document.write("s.setAttribute(\'src\',url);");
document.writeln('');document.write("s.onload = s.onreadystatechange = function(){");
document.writeln('');document.write("if(!this.readyState || this.readyState === \'loaded\' || this.readyState === \'complete\'){");
document.writeln('');document.write("s.onload = s.onreadystatechange = null;");
document.writeln('');document.write("callback();");
document.writeln('');document.write("}");
document.writeln('');document.write("}");
document.writeln('');document.write("this.GN(\'head\')[0].appendChild(s);");
document.writeln('');document.write("}");
document.writeln('');document.write("");
document.writeln('');document.write("};");
document.writeln('');document.write("");
document.writeln('');document.write("");
document.writeln('');document.write("");
document.writeln('');document.write("// Placeholder constructor");
document.writeln('');document.write("var PHConstructor = function(wrap) {");
document.writeln('');document.write("this.wrap = wrap;");
document.writeln('');document.write("this.init.apply(this, arguments);");
document.writeln('');document.write("};");
document.writeln('');document.write("");
document.writeln('');document.write("PHConstructor.prototype = {");
document.writeln('');document.write("constructor : PHConstructor,");
document.writeln('');document.write("init : function() {");
document.writeln('');document.write("if (supportPlaceHolder) { return }");
document.writeln('');document.write("var me = this;");
document.writeln('');document.write("var inputs = utils.GA(\'supportplaceholder\', me.wrap, \'INPUT\');");
document.writeln('');document.write("var inputsLength = inputs.length, i = 0;");
document.writeln('');document.write("while (i < inputsLength) {");
document.writeln('');document.write("me.build(inputs[i]);");
document.writeln('');document.write("i++;");
document.writeln('');document.write("}");
document.writeln('');document.write("}");
document.writeln('');document.write(", build : function(obj) {");
document.writeln('');document.write("var type = obj.getAttribute(\"type\");");
document.writeln('');document.write("var holderValue = obj.getAttribute(\"supportplaceholder\");");
document.writeln('');document.write("switch(type) {");
document.writeln('');document.write("case \'password\' :");
document.writeln('');document.write("var holderInput = utils.GN(\'INPUT\', obj.parentNode)[0];");
document.writeln('');document.write("holderInput.style.display = \'block\';");
document.writeln('');document.write("utils.addEvent(holderInput, \'focus\', function() {");
document.writeln('');document.write("holderInput.style.display = \'none\';");
document.writeln('');document.write("obj.focus();");
document.writeln('');document.write("});");
document.writeln('');document.write("utils.addEvent(obj, \'blur\', function(e) {");
document.writeln('');document.write("if (utils.trim(obj.value) === \'\') {");
document.writeln('');document.write("holderInput.style.display = \'block\';");
document.writeln('');document.write("}");
document.writeln('');document.write("});");
document.writeln('');document.write("break;");
document.writeln('');document.write("");
document.writeln('');document.write("default :");
document.writeln('');document.write("obj.value = holderValue;");
document.writeln('');document.write("utils.addEvent(obj, \'focus\', function(e) {");
document.writeln('');document.write("if (utils.trim(obj.value) === holderValue) {");
document.writeln('');document.write("obj.value = \'\';");
document.writeln('');document.write("}");
document.writeln('');document.write("});");
document.writeln('');document.write("utils.addEvent(obj, \'blur\', function(e) {");
document.writeln('');document.write("if (utils.trim(obj.value) === \'\') {");
document.writeln('');document.write("obj.value = holderValue;");
document.writeln('');document.write("}");
document.writeln('');document.write("});");
document.writeln('');document.write("break;");
document.writeln('');document.write("}");
document.writeln('');document.write("}");
document.writeln('');document.write("};");
document.writeln('');document.write("");
document.writeln('');document.write("var wrap = utils.GD(WRAP_ID);");
document.writeln('');document.write("var needlogin = ( wrap.getAttribute(\'needlogin\') === \"1\" );");
document.writeln('');document.write("var formElement = utils.GN(\'FORM\', wrap)[0];");
document.writeln('');document.write("var loginblk = utils.GC(\'sv_login_box\', wrap, \'DIV\')[0];");
document.writeln('');document.write("var logintitle = utils.GC(\'sv_login_title\', wrap, \'DIV\')[0];");
document.writeln('');document.write("var loginLayerTrigger = utils.GC(\'sv_login_btn\', logintitle, \'A\')[0];");
document.writeln('');document.write("var loginLayerCloser = utils.GC(\'sv_box_closer\', loginblk, \'A\')[0];");
document.writeln('');document.write("var submitBtn = utils.GN(\'INPUT\', utils.GC(\'sv_buttons\', wrap, \'DIV\')[0])[0];");
document.writeln('');document.write("var unableSubmitBtn = utils.GC(\'sv_unablesubmit\', wrap, \'SPAN\')[0];");
document.writeln('');document.write("var joinedBtn = utils.GC(\'sv_joined\', wrap, \'SPAN\')[0];");
document.writeln('');document.write("var errortip = utils.GC(\'sv_login_error\', loginblk, \'DIV\')[0];");
document.writeln('');document.write("var loginBtn = utils.GC(\'sv_handler_login\', loginblk, \'A\')[0];");
document.writeln('');document.write("");
document.writeln('');document.write("var setBtnstatus = function( login, join ) {");
document.writeln('');document.write("if ( !login ) {");
document.writeln('');document.write("logintitle.style.display = \'block\';");
document.writeln('');document.write("submitBtn.style.display = \'none\';");
document.writeln('');document.write("unableSubmitBtn.style.display = \'inline-block\';");
document.writeln('');document.write("joinedBtn.style.display = \'none\';");
document.writeln('');document.write("} else {");
document.writeln('');document.write("logintitle.style.display = \'none\';");
document.writeln('');document.write("unableSubmitBtn.style.display = \'none\';");
document.writeln('');document.write("if ( join ) {");
document.writeln('');document.write("submitBtn.style.display = \'none\';");
document.writeln('');document.write("joinedBtn.style.display = \'inline-block\';");
document.writeln('');document.write("} else {");
document.writeln('');document.write("submitBtn.style.display = \'inline-block\';");
document.writeln('');document.write("joinedBtn.style.display = \'none\';");
document.writeln('');document.write("}");
document.writeln('');document.write("}");
document.writeln('');document.write("};");
document.writeln('');document.write("");
document.writeln('');document.write("if ( needlogin ) {");
document.writeln('');document.write("");
document.writeln('');document.write("var pid = utils.GAC(\'poll_id\', \'name\', wrap, \'INPUT\')[0].value;");
document.writeln('');document.write("var inputs = utils.GN(\'INPUT\', formElement);");
document.writeln('');document.write("var textareas = utils.GN(\'TEXTAREA\', formElement);");
document.writeln('');document.write("var selects = utils.GN(\'SELECT\', formElement);");
document.writeln('');document.write("var counter = 0;");
document.writeln('');document.write("var _jointimehandler = null;");
document.writeln('');document.write("");
document.writeln('');document.write("var showError = function(msg, flag) {");
document.writeln('');document.write("flag ? errortip.className = \'sv_login_error sv_need_login\' : errortip.className = \'sv_login_error\';");
document.writeln('');document.write("errortip.innerHTML = msg;");
document.writeln('');document.write("errortip.style.visibility = \'visible\';");
document.writeln('');document.write("};");
document.writeln('');document.write("var hideError = function() {");
document.writeln('');document.write("errortip.style.visibility = \'hidden\';");
document.writeln('');document.write("};");
document.writeln('');document.write("var isLogin = function() {");
document.writeln('');document.write("return !!utils.getcookie(\'SUP\');");
document.writeln('');document.write("};");
document.writeln('');document.write("");
document.writeln('');document.write("var disabledForm = function() {");
document.writeln('');document.write("var inputsLen = inputs.length,");
document.writeln('');document.write("textareasLen = textareas.length,");
document.writeln('');document.write("selectsLen = selects.length;");
document.writeln('');document.write("i = 0, j = 0, k = 0;");
document.writeln('');document.write("while( i < inputsLen ) {");
document.writeln('');document.write("inputs[i].setAttribute(\'disabled\', true);");
document.writeln('');document.write("i++;");
document.writeln('');document.write("}");
document.writeln('');document.write("while( j < textareasLen ) {");
document.writeln('');document.write("textareas[j].setAttribute(\'disabled\', true);");
document.writeln('');document.write("j++;");
document.writeln('');document.write("}");
document.writeln('');document.write("while( k < selectsLen ) {");
document.writeln('');document.write("selects[k].setAttribute(\'disabled\', true);");
document.writeln('');document.write("k++;");
document.writeln('');document.write("}");
document.writeln('');document.write("};");
document.writeln('');document.write("");
document.writeln('');document.write("var resetForm = function() {");
document.writeln('');document.write("var inputsLen = inputs.length,");
document.writeln('');document.write("textareasLen = textareas.length,");
document.writeln('');document.write("selectsLen = selects.length;");
document.writeln('');document.write("i = 0, j = 0, k = 0;");
document.writeln('');document.write("while( i < inputsLen ) {");
document.writeln('');document.write("inputs[i].removeAttribute(\'disabled\');");
document.writeln('');document.write("i++;");
document.writeln('');document.write("}");
document.writeln('');document.write("while( j < textareasLen ) {");
document.writeln('');document.write("textareas[j].removeAttribute(\'disabled\');");
document.writeln('');document.write("j++;");
document.writeln('');document.write("}");
document.writeln('');document.write("while( k < selectsLen ) {");
document.writeln('');document.write("selects[k].removeAttribute(\'disabled\');");
document.writeln('');document.write("k++;");
document.writeln('');document.write("}");
document.writeln('');document.write("};");
document.writeln('');document.write("");
document.writeln('');document.write("var getJoinedStatus = function() {");
document.writeln('');document.write("var uid = (window.SINA_OUTLOGIN_LAYER && window.SINA_OUTLOGIN_LAYER.getSinaCookie()) ? window.SINA_OUTLOGIN_LAYER.getSinaCookie().uid : \'\';");
document.writeln('');document.write("utils.jsonp(\'http://survey.news.sina.com.cn/survey_js.php\',\'t=user_data&format=json&pid=\' + pid + \'&uid=\' + uid, function(data) {");
document.writeln('');document.write("if (data.result.status.code === 0) {");
document.writeln('');document.write("var msg = data.result.data;");
document.writeln('');document.write("if (msg.length > 0) {");
document.writeln('');document.write("setBtnstatus(true, true);");
document.writeln('');document.write("disabledForm();");
document.writeln('');document.write("_jointimehandler && clearTimeout(_jointimehandler);");
document.writeln('');document.write("} else {");
document.writeln('');document.write("if (counter === 0) {");
document.writeln('');document.write("setBtnstatus(true, false);");
document.writeln('');document.write("}");
document.writeln('');document.write("if (counter < 3) {");
document.writeln('');document.write("_jointimehandler = setTimeout(function() {");
document.writeln('');document.write("counter++;");
document.writeln('');document.write("getJoinedStatus();");
document.writeln('');document.write("}, 1100);");
document.writeln('');document.write("} else {");
document.writeln('');document.write("_jointimehandler && clearTimeout(_jointimehandler);");
document.writeln('');document.write("}");
document.writeln('');document.write("}");
document.writeln('');document.write("} else {");
document.writeln('');document.write("setBtnstatus(true, false);");
document.writeln('');document.write("}");
document.writeln('');document.write("});");
document.writeln('');document.write("};");
document.writeln('');document.write("var checkJoinedStatus = function() {");
document.writeln('');document.write("getJoinedStatus();");
document.writeln('');document.write("};");
document.writeln('');document.write("");
document.writeln('');document.write("var inited = false;");
document.writeln('');document.write("var loginControl = function() {");
document.writeln('');document.write("if ( needlogin && !isLogin() ) {");
document.writeln('');document.write("if (!inited) {");
document.writeln('');document.write("new PHConstructor(utils.GD(WRAP_ID));");
document.writeln('');document.write("inited = true;");
document.writeln('');document.write("}");
document.writeln('');document.write("setBtnstatus(false, false);");
document.writeln('');document.write("resetForm();");
document.writeln('');document.write("} else {");
document.writeln('');document.write("//checkJoinedStatus();");
document.writeln('');document.write("}");
document.writeln('');document.write("}");
document.writeln('');document.write("if(isLogin()) { checkJoinedStatus(); }");
document.writeln('');document.write("loginControl();");
document.writeln('');document.write("window.___Survey_TimeHandler___ = setInterval(function() {");
document.writeln('');document.write("loginControl();");
document.writeln('');document.write("}, 10000);");
document.writeln('');document.write("");
document.writeln('');document.write("");
document.writeln('');document.write("// Username & password checking");
document.writeln('');document.write(";(function() {");
document.writeln('');document.write("");
document.writeln('');document.write("var loginCache = null;");
document.writeln('');document.write("var isLogining = false;");
document.writeln('');document.write("var preventDefault = function(e) {");
document.writeln('');document.write("var e = e||window.event;");
document.writeln('');document.write("try {");
document.writeln('');document.write("e.preventDefault();");
document.writeln('');document.write("} catch(e) {");
document.writeln('');document.write("e.returnValue = false;");
document.writeln('');document.write("}");
document.writeln('');document.write("};");
document.writeln('');document.write("");
document.writeln('');document.write("");
document.writeln('');document.write("var usernameipt = utils.GN(\'INPUT\', utils.GC(\'sv_username\', wrap, \'DIV\')[0])[0];");
document.writeln('');document.write("var passwordipt = utils.GN(\'INPUT\', utils.GC(\'sv_password\', wrap, \'DIV\')[0])[1];");
document.writeln('');document.write("");
document.writeln('');document.write("var getSSO = function(_SSOController) {");
document.writeln('');document.write("window[WRAP_ID] = new _SSOController();");
document.writeln('');document.write("var sc = window[WRAP_ID];");
document.writeln('');document.write("sc.init();");
document.writeln('');document.write("(function(){");
document.writeln('');document.write("this.name = WRAP_ID;");
document.writeln('');document.write("this.entry = \"sso\";");
document.writeln('');document.write("this.domain = \"sina.com.cn\";");
document.writeln('');document.write("this.setDomain = true;");
document.writeln('');document.write("this.customLoginCallBack = function(loginStatus) {");
document.writeln('');document.write("if (loginStatus.result/* && !loginCache*/) {");
document.writeln('');document.write("// formElement.submit();");
document.writeln('');document.write("loginblk.style.display = \'none\';");
document.writeln('');document.write("logintitle.style.display = \'none\';");
document.writeln('');document.write("isLogining = false;");
document.writeln('');document.write("counter = 0;");
document.writeln('');document.write("checkJoinedStatus();");
document.writeln('');document.write("} else {");
document.writeln('');document.write("if (!loginStatus.reason) {");
document.writeln('');document.write("showError(\"\\u8BF7\\u8F93\\u5165\\u8D26\\u53F7\\u548C\\u5BC6\\u7801\");");
document.writeln('');document.write("} else {");
document.writeln('');document.write("showError(loginStatus.reason);");
document.writeln('');document.write("}");
document.writeln('');document.write("}");
document.writeln('');document.write("};");
document.writeln('');document.write("this.customLogoutCallBack = function (result) {");
document.writeln('');document.write("");
document.writeln('');document.write("};");
document.writeln('');document.write("");
document.writeln('');document.write("}).apply(sc);");
document.writeln('');document.write("};");
document.writeln('');document.write("if ( !window.SSOController ) {");
document.writeln('');document.write("utils.jsLoader(\'http://i.sso.sina.com.cn/js/ssologin.js\', function() {");
document.writeln('');document.write("getSSO(window.SSOController);");
document.writeln('');document.write("});");
document.writeln('');document.write("} else {");
document.writeln('');document.write("getSSO(window.SSOController);");
document.writeln('');document.write("}");
document.writeln('');document.write("");
document.writeln('');document.write("var loginit = function() {");
document.writeln('');document.write("var username = usernameipt.value;");
document.writeln('');document.write("var password = passwordipt.value;");
document.writeln('');document.write("");
document.writeln('');document.write("if (username === usernameipt.getAttribute(\'supportplaceholder\')) {");
document.writeln('');document.write("username = \"\";");
document.writeln('');document.write("}");
document.writeln('');document.write("if (password === passwordipt.getAttribute(\'supportplaceholder\')) {");
document.writeln('');document.write("password = \"\";");
document.writeln('');document.write("}");
document.writeln('');document.write("");
document.writeln('');document.write("window[WRAP_ID].login(username, password);");
document.writeln('');document.write("return false;");
document.writeln('');document.write("};");
document.writeln('');document.write("utils.addEvent(loginBtn, \'click\', function(e) {");
document.writeln('');document.write("loginit();");
document.writeln('');document.write("});");
document.writeln('');document.write("utils.addEvent(loginblk, \'keydown\', function(e) {");
document.writeln('');document.write("var e = e || window.event;");
document.writeln('');document.write("if (e.keyCode == 13) {");
document.writeln('');document.write("loginit();");
document.writeln('');document.write("}");
document.writeln('');document.write("});");
document.writeln('');document.write("utils.addEvent(loginLayerTrigger, \'click\', function(e) {");
document.writeln('');document.write("loginblk.style.display = \'block\';");
document.writeln('');document.write("isLogining = true;");
document.writeln('');document.write("});");
document.writeln('');document.write("utils.addEvent(loginLayerCloser, \'click\', function(e) {");
document.writeln('');document.write("loginblk.style.display = \'none\';");
document.writeln('');document.write("isLogining = false;");
document.writeln('');document.write("});");
document.writeln('');document.write("utils.addEvent(formElement, \'submit\', function(e) {");
document.writeln('');document.write("if ( isLogining ) {");
document.writeln('');document.write("preventDefault(e);");
document.writeln('');document.write("return false;");
document.writeln('');document.write("} else {");
document.writeln('');document.write("counter = 0;");
document.writeln('');document.write("checkJoinedStatus();");
document.writeln('');document.write("return true;");
document.writeln('');document.write("}");
document.writeln('');document.write("});");
document.writeln('');document.write("})();");
document.writeln('');document.write("} else {");
document.writeln('');document.write("submitBtn.style.display = \'inline-block\';");
document.writeln('');document.write("loginblk.style.display = \'none\';");
document.writeln('');document.write("}");
document.writeln('');document.write("");
document.writeln('');document.write("})(window);");
document.writeln('');document.write("</s");document.write("cript>");
document.writeln('');document.write("");
document.writeln('');document.write("");
document.writeln('');